"""Twilio SMS dispatch service."""

from __future__ import annotations

import os

from twilio.rest import Client


def send_referral_sms(abha_id: str | None, risk_level: str, timestamp: str, device_id: str) -> bool:
    account_sid = os.getenv("TWILIO_ACCOUNT_SID")
    auth_token = os.getenv("TWILIO_AUTH_TOKEN")
    from_number = os.getenv("TWILIO_FROM_NUMBER")
    to_number = os.getenv("DISTRICT_HOSPITAL_NUMBER")

    if not all([account_sid, auth_token, from_number, to_number]):
        print("SMS skipped: Twilio env vars are not fully configured")
        return False

    client = Client(account_sid, auth_token)
    abha_display = abha_id if abha_id else f"Device-{device_id[:8]}"
    message_body = (
        "MATERNAGUARD ALERT\n"
        "HIGH RISK PREGNANCY DETECTED\n"
        f"Patient ABHA ID: {abha_display}\n"
        f"Risk level: {risk_level.upper()}\n"
        f"Assessment time: {timestamp}\n"
        "Action required: Prepare for referral from local PHC.\n"
        "This alert was generated by MaternaGuard AI."
    )

    try:
        message = client.messages.create(body=message_body, from_=from_number, to=to_number)
        print(f"SMS sent: SID={message.sid}, to={to_number}")
        return True
    except Exception as exc:
        print(f"SMS failed: {exc}")
        return False
